"""Add Control Plane and Redesign Data Layer

Revision ID: 2be4d70ae3d7
Revises: 
Create Date: 2026-02-16 15:52:37.613524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be4d70ae3d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.String(), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_id')
    )
    op.create_index(op.f('ix_checkpoints_customer_id'), 'checkpoints', ['customer_id'], unique=False)
    op.create_table('client_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contexts_customer_id'), 'client_contexts', ['customer_id'], unique=False)
    op.create_table('platform_tenants',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('cost_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trace_id')
    )
    op.create_index(op.f('ix_agent_runs_customer_id'), 'agent_runs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_ticket_id'), 'agent_runs', ['ticket_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_customer_id'), 'audit_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_ticket_id'), 'audit_logs', ['ticket_id'], unique=False)
    op.create_table('capability_scopes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('scope_name', sa.String(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['platform_tenants.customer_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_scopes_customer_id'), 'capability_scopes', ['customer_id'], unique=False)
    op.create_table('evidence_refs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('storage_ref', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_refs_customer_id'), 'evidence_refs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_evidence_refs_ticket_id'), 'evidence_refs', ['ticket_id'], unique=False)
    op.create_table('tenant_endpoints',
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('pg_dsn_ref', sa.String(), nullable=True),
    sa.Column('qdrant_url_ref', sa.String(), nullable=True),
    sa.Column('object_store_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['platform_tenants.customer_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('agent_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_customer_id'), 'agent_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    op.create_table('tool_calls_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args_redacted', sa.JSON(), nullable=False),
    sa.Column('result_meta', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_audit_customer_id'), 'tool_calls_audit', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_audit_run_id'), 'tool_calls_audit', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_audit_run_id'), table_name='tool_calls_audit')
    op.drop_index(op.f('ix_tool_calls_audit_customer_id'), table_name='tool_calls_audit')
    op.drop_table('tool_calls_audit')
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_customer_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_table('tenant_endpoints')
    op.drop_index(op.f('ix_evidence_refs_ticket_id'), table_name='evidence_refs')
    op.drop_index(op.f('ix_evidence_refs_customer_id'), table_name='evidence_refs')
    op.drop_table('evidence_refs')
    op.drop_index(op.f('ix_capability_scopes_customer_id'), table_name='capability_scopes')
    op.drop_table('capability_scopes')
    op.drop_index(op.f('ix_audit_logs_ticket_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_customer_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agent_runs_ticket_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_customer_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('platform_tenants')
    op.drop_index(op.f('ix_client_contexts_customer_id'), table_name='client_contexts')
    op.drop_table('client_contexts')
    op.drop_index(op.f('ix_checkpoints_customer_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    # ### end Alembic commands ###
