"""s1_tenant_fk_on_tenant_mixin

Revision ID: 732204a5c63e
Revises: 84d82b83283a
Create Date: 2026-02-27 16:08:38.297314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732204a5c63e'
down_revision: Union[str, None] = '84d82b83283a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Data cleanup: delete orphan rows before adding FK constraints ---
    # agent_events references agent_runs, so delete child rows first.
    op.execute(sa.text("""
        DELETE FROM agent_events
        WHERE run_id IN (
            SELECT id FROM agent_runs
            WHERE customer_id NOT IN (SELECT customer_id FROM platform_tenants)
        )
    """))
    # Now delete the orphan agent_runs themselves.
    op.execute(sa.text("""
        DELETE FROM agent_runs
        WHERE customer_id NOT IN (SELECT customer_id FROM platform_tenants)
    """))
    # Delete any other orphan rows across remaining data-plane tables.
    for table in ('audit_logs', 'checkpoints', 'client_contexts', 'evidence_refs', 'tickets', 'tool_calls_audit'):
        op.execute(sa.text(
            f"DELETE FROM {table} WHERE customer_id NOT IN (SELECT customer_id FROM platform_tenants)"
        ))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent_events', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'agent_runs', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'audit_logs', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'checkpoints', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'client_contexts', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'evidence_refs', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'tickets', 'platform_tenants', ['customer_id'], ['customer_id'])
    op.create_foreign_key(None, 'tool_calls_audit', 'platform_tenants', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_calls_audit', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'evidence_refs', type_='foreignkey')
    op.drop_constraint(None, 'client_contexts', type_='foreignkey')
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_constraint(None, 'agent_events', type_='foreignkey')
    # ### end Alembic commands ###
