"""tenant_isolation_schema_fixes

Revision ID: 84d82b83283a
Revises: efaae4bb2b50
Create Date: 2026-02-27 15:48:29.127195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d82b83283a'
down_revision: Union[str, None] = 'efaae4bb2b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agent_events_run_seq', 'agent_events', ['run_id', 'seq'], unique=False)
    op.drop_constraint(op.f('agent_events_run_id_fkey'), 'agent_events', type_='foreignkey')
    op.create_foreign_key(None, 'agent_events', 'agent_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.add_column('agent_runs', sa.Column('final_answer', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('hypothesis_count', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('decision', sa.String(), nullable=True))
    op.create_index('ix_agent_runs_tenant_ticket', 'agent_runs', ['customer_id', 'ticket_id'], unique=False)
    op.drop_constraint(op.f('agent_runs_ticket_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_logs_ticket_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_scope_per_tenant', 'capability_scopes', ['customer_id', 'scope_name'])
    op.create_index('ix_client_contexts_tenant_active', 'client_contexts', ['customer_id', 'is_active'], unique=False)
    # Data cleanup: deactivate all but the most recent active context per tenant
    # before creating the unique partial index (S2).
    op.execute(sa.text("""
        UPDATE client_contexts SET is_active = false
        WHERE id NOT IN (
            SELECT DISTINCT ON (customer_id) id
            FROM client_contexts
            WHERE is_active = true
            ORDER BY customer_id, created_at DESC
        )
        AND is_active = true
    """))
    op.create_index('uq_client_context_active', 'client_contexts', ['customer_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.drop_constraint(op.f('evidence_refs_ticket_id_fkey'), 'evidence_refs', type_='foreignkey')
    op.create_foreign_key(None, 'evidence_refs', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.add_column('platform_tenants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_tickets_tenant_created', 'tickets', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_tool_calls_run_status', 'tool_calls_audit', ['run_id', 'status'], unique=False)
    op.drop_constraint(op.f('tool_calls_audit_run_id_fkey'), 'tool_calls_audit', type_='foreignkey')
    op.create_foreign_key(None, 'tool_calls_audit', 'agent_runs', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_calls_audit', type_='foreignkey')
    op.create_foreign_key(op.f('tool_calls_audit_run_id_fkey'), 'tool_calls_audit', 'agent_runs', ['run_id'], ['id'])
    op.drop_index('ix_tool_calls_run_status', table_name='tool_calls_audit')
    op.drop_index('ix_tickets_tenant_created', table_name='tickets')
    op.drop_column('platform_tenants', 'updated_at')
    op.drop_constraint(None, 'evidence_refs', type_='foreignkey')
    op.create_foreign_key(op.f('evidence_refs_ticket_id_fkey'), 'evidence_refs', 'tickets', ['ticket_id'], ['id'])
    op.drop_index('uq_client_context_active', table_name='client_contexts', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_client_contexts_tenant_active', table_name='client_contexts')
    op.drop_constraint('uq_scope_per_tenant', 'capability_scopes', type_='unique')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_ticket_id_fkey'), 'audit_logs', 'tickets', ['ticket_id'], ['id'])
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_runs_ticket_id_fkey'), 'agent_runs', 'tickets', ['ticket_id'], ['id'])
    op.drop_index('ix_agent_runs_tenant_ticket', table_name='agent_runs')
    op.drop_column('agent_runs', 'decision')
    op.drop_column('agent_runs', 'hypothesis_count')
    op.drop_column('agent_runs', 'final_answer')
    op.drop_constraint(None, 'agent_events', type_='foreignkey')
    op.create_foreign_key(op.f('agent_events_run_id_fkey'), 'agent_events', 'agent_runs', ['run_id'], ['id'])
    op.drop_index('ix_agent_events_run_seq', table_name='agent_events')
    # ### end Alembic commands ###
