"""fix ticket updated_at default

Revision ID: efaae4bb2b50
Revises: 2be4d70ae3d7
Create Date: 2026-02-26 15:56:43.541575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaae4bb2b50'
down_revision: Union[str, None] = '2be4d70ae3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at', server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at', server_default=None)
    # ### end Alembic commands ###
