"""FortiEDR pack contract tests.

The specs in ``vendors/fortinet/fortiedr/6.2/specs/mgmt/`` are generated by
``scripts/convert_fortiedr_specs.py`` from the raw Swagger 2.0 exports in
``FortiEDR/swagger/v6.2/``. These tests pin the conversion contract: valid
OpenAPI 3 shape, converter-generated operationIds, and the safety-name
invariants the app-side keyword filter relies on.
"""

import json
import sys
from pathlib import Path

import pytest

GATEWAY_ROOT = Path(__file__).resolve().parents[2]
SPECS_DIR = GATEWAY_ROOT / "vendors" / "fortinet" / "fortiedr" / "6.2" / "specs" / "mgmt"

sys.path.insert(0, str(GATEWAY_ROOT / "scripts"))

from convert_fortiedr_specs import (  # noqa: E402
    AREA_DESCRIPTION_NOTES,
    BLOCKED_NAME_KEYWORDS,
    HTTP_METHODS,
    QUERY_PARAM_ENRICHMENTS,
    READ_EXEMPT,
)

SPEC_PATHS = sorted(SPECS_DIR.glob("fortiedr_*.json"))


def _operations(spec):
    for path, item in spec["paths"].items():
        for method, op in item.items():
            if method in HTTP_METHODS:
                yield path, method, op


def test_expected_spec_count():
    assert len(SPEC_PATHS) == 26


def test_manifest_uses_global_http_timeout():
    # No per-pack override: the pack rides the global GATEWAY_HTTP_TIMEOUT
    # default (30s, raised from 10s for the cloud console's org-wide queries).
    import yaml

    from gateway.vendor_pack import ApplianceManifest

    manifest_path = GATEWAY_ROOT / "vendors" / "fortinet" / "fortiedr" / "6.2" / "manifest.yaml"
    manifest = ApplianceManifest(**yaml.safe_load(manifest_path.read_text(encoding="utf-8")))
    assert manifest.http_timeout is None
    assert manifest.http_connect_timeout is None


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_spec_is_openapi3(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    assert spec["openapi"] == "3.0.3"
    assert "swagger" not in spec
    assert "basePath" not in spec
    assert "definitions" not in spec
    assert spec["servers"] == [{"url": "/"}]
    assert "#/definitions/" not in spec_path.read_text(encoding="utf-8")


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_operation_ids_unique_per_file(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    op_ids = [op["operationId"] for _, _, op in _operations(spec)]
    assert len(op_ids) == len(set(op_ids))


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_safety_name_invariants(spec_path):
    """GETs carry the _get read-only marker; mutating ops carry a blocked
    keyword so the app-side name filter hides them (READ_EXEMPT aside)."""
    area = spec_path.stem.removeprefix("fortiedr_")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    for path, method, op in _operations(spec):
        name = f"fedr62_mgmt_{area}_{op['operationId']}".lower()
        if (area, method, path) in READ_EXEMPT:
            continue
        blocked = any(kw in name for kw in BLOCKED_NAME_KEYWORDS)
        if method == "get":
            assert "_get" in name or blocked, f"{method.upper()} {path} -> {name}"
        else:
            assert blocked, f"{method.upper()} {path} -> {name}"


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_no_swagger2_param_style(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    for path, method, op in _operations(spec):
        assert "produces" not in op and "consumes" not in op
        for param in op.get("parameters", []):
            assert param["in"] in ("query", "path", "header"), (path, param)
            assert "schema" in param and "type" not in param, (path, param)
        for resp in op["responses"].values():
            assert "schema" not in resp, (path, method)


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_query_param_enrichments_applied(spec_path):
    """Enriched query params carry the live-verified schema and description,
    not the raw export's. The raw Springfox exports ship partial ``timeFilter``
    enums that the appliance rejects at runtime (the live parser, verified
    against a real 6.2 console for both the incidents and dashboard endpoint
    families, shares one server-side enum parser and accepts the 8-value union
    pinned in ``QUERY_PARAM_ENRICHMENTS``), and under-documented params
    (epoch unit, organization-id provenance) whose curated descriptions
    REPLACE the raw ones."""
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    for path, method, op in _operations(spec):
        for param in op.get("parameters", []):
            enrich = QUERY_PARAM_ENRICHMENTS.get(param["name"])
            if not enrich or param["in"] != "query":
                continue
            # Applied to every occurrence — including ones the raw export left
            # enum-less (e.g. raw-events' required timeFilter): same parser.
            if "enum" in enrich:
                assert param["schema"].get("enum") == enrich["enum"], (
                    spec_path.stem, path, method, param["name"],
                )
            if "description" in enrich:
                assert param.get("description") == enrich["description"], (
                    spec_path.stem, path, method, param["name"],
                )


def test_enrichment_keys_are_live_verified():
    """Guard against casually widening the enrichment table: every entry here
    must have been verified against a live console (see the table's comments
    for the 2026-07-23 evidence per key)."""
    assert set(QUERY_PARAM_ENRICHMENTS) == {
        "timeFilter", "startDate", "endDate", "organizationId", "device",
        "firstSeenFrom", "firstSeenTo", "lastSeenFrom", "lastSeenTo",
    }
    # Events-family dates are strings with a space separator — the opposite
    # idiom to the incidents family's epoch milliseconds. Both formats and
    # their rejection modes are live-verified; keep them spelled out.
    for key in ("firstSeenFrom", "firstSeenTo", "lastSeenFrom", "lastSeenTo"):
        assert "yyyy-MM-dd HH:mm:ss" in QUERY_PARAM_ENRICHMENTS[key]["description"]
    assert QUERY_PARAM_ENRICHMENTS["timeFilter"]["enum"] == [
        "Last1days", "Last7days", "Last14days", "Last30days",
        "Last60days", "Last90days", "All", "Custom",
    ]
    # The epoch-unit trap fails silently (seconds -> empty result, no error) —
    # the milliseconds requirement must stay spelled out.
    for key in ("startDate", "endDate"):
        assert "MILLISECONDS" in QUERY_PARAM_ENRICHMENTS[key]["description"]
    assert "accountId" in QUERY_PARAM_ENRICHMENTS["organizationId"]["description"]
    # The routing-habit trap fails silently (component id -> 200 with 0
    # results) — the OMIT guidance must stay spelled out.
    assert "OMIT" in QUERY_PARAM_ENRICHMENTS["device"]["description"]
    assert "routing" in QUERY_PARAM_ENRICHMENTS["device"]["description"]


def test_area_notes_are_live_verified():
    """Same rule as the enrichment table: an area-wide description note must be
    backed by live console evidence. 2026-07-23: every GET under
    /api/incidents/mobile and /api/inventory/mobile answered HTTP 404 on a
    console without the mobile module, while the raw descriptions ("Get
    incidents") read as drop-in alternatives to the main endpoints."""
    assert set(AREA_DESCRIPTION_NOTES) == {"mobile", "mobile_inventory"}
    for note in AREA_DESCRIPTION_NOTES.values():
        assert "404" in note and "module" in note


@pytest.mark.parametrize("area", sorted(AREA_DESCRIPTION_NOTES), ids=str)
def test_area_notes_applied_to_every_operation(area):
    spec = json.loads((SPECS_DIR / f"fortiedr_{area}.json").read_text(encoding="utf-8"))
    note = AREA_DESCRIPTION_NOTES[area]
    for path, method, op in _operations(spec):
        assert note in op.get("description", ""), (area, path, method)


def test_baseline_contains_fedr_tools():
    baseline = (GATEWAY_ROOT / "baseline_tools.txt").read_text(encoding="utf-8").splitlines()
    fedr = [n for n in baseline if n.startswith("fedr62_")]
    assert len(fedr) == 230  # 229 operations + fedr62_get_inventory_tree
    assert "fedr62_get_inventory_tree" in fedr
