"""FortiEDR pack contract tests.

The specs in ``vendors/fortinet/fortiedr/specs/mgmt/`` are generated by
``scripts/convert_fortiedr_specs.py`` from the raw Swagger 2.0 exports in
``FortiEDR/swagger/v6.2/``. These tests pin the conversion contract: valid
OpenAPI 3 shape, converter-generated operationIds, and the safety-name
invariants the app-side keyword filter relies on.
"""

import json
import sys
from pathlib import Path

import pytest

GATEWAY_ROOT = Path(__file__).resolve().parents[2]
SPECS_DIR = GATEWAY_ROOT / "vendors" / "fortinet" / "fortiedr" / "specs" / "mgmt"

sys.path.insert(0, str(GATEWAY_ROOT / "scripts"))

from convert_fortiedr_specs import (  # noqa: E402
    BLOCKED_NAME_KEYWORDS,
    HTTP_METHODS,
    READ_EXEMPT,
)

SPEC_PATHS = sorted(SPECS_DIR.glob("fortiedr_*.json"))


def _operations(spec):
    for path, item in spec["paths"].items():
        for method, op in item.items():
            if method in HTTP_METHODS:
                yield path, method, op


def test_expected_spec_count():
    assert len(SPEC_PATHS) == 26


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_spec_is_openapi3(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    assert spec["openapi"] == "3.0.3"
    assert "swagger" not in spec
    assert "basePath" not in spec
    assert "definitions" not in spec
    assert spec["servers"] == [{"url": "/"}]
    assert "#/definitions/" not in spec_path.read_text(encoding="utf-8")


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_operation_ids_unique_per_file(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    op_ids = [op["operationId"] for _, _, op in _operations(spec)]
    assert len(op_ids) == len(set(op_ids))


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_safety_name_invariants(spec_path):
    """GETs carry the _get read-only marker; mutating ops carry a blocked
    keyword so the app-side name filter hides them (READ_EXEMPT aside)."""
    area = spec_path.stem.removeprefix("fortiedr_")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    for path, method, op in _operations(spec):
        name = f"fedr_mgmt_{area}_{op['operationId']}".lower()
        if (area, method, path) in READ_EXEMPT:
            continue
        blocked = any(kw in name for kw in BLOCKED_NAME_KEYWORDS)
        if method == "get":
            assert "_get" in name or blocked, f"{method.upper()} {path} -> {name}"
        else:
            assert blocked, f"{method.upper()} {path} -> {name}"


@pytest.mark.parametrize("spec_path", SPEC_PATHS, ids=lambda p: p.stem)
def test_no_swagger2_param_style(spec_path):
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    for path, method, op in _operations(spec):
        assert "produces" not in op and "consumes" not in op
        for param in op.get("parameters", []):
            assert param["in"] in ("query", "path", "header"), (path, param)
            assert "schema" in param and "type" not in param, (path, param)
        for resp in op["responses"].values():
            assert "schema" not in resp, (path, method)


def test_baseline_contains_fedr_tools():
    baseline = (GATEWAY_ROOT / "baseline_tools.txt").read_text(encoding="utf-8").splitlines()
    fedr = [n for n in baseline if n.startswith("fedr_")]
    assert len(fedr) == 230  # 229 operations + fedr_get_inventory_tree
    assert "fedr_get_inventory_tree" in fedr
